### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by tibawatanabe** [ChrisAmora/onboard#2]
In this issue, you will have to:

# Task 1 - Create a git branch

- [ ] Create a branch called `feature/setup`

If you don't remember how to create a branch, check the references in the previous issues.

# Task 2 - Create a simple Hello World

- [ ] Follow a tutorial of your choice to create a minimal "Hello World" project

# Task 3 - Create a Pull Request

- [ ] Open a Pull Request with your modifications

If you don't remember how to open a Pull Request, check the references in the previous issues.

**Note**: From here, the issues will contain fewer tutorials and step-by-step guides. However, it doesn't mean you won't be able to ask. You can always ask **anything** to **any** Taqtiler. We are here to help 😉

**Note 2:** Be patient, this is the last setup before coding. 👍
